### ISSUE TITLE
Traits do not seem to be remembered if you change them and request soon after

### ISSUE THREAD

**Issue by mjwills-k** [Flagsmith/flagsmith-dotnet-client#123]
The below unit test fails some / most of the time, unless you uncomment `// Thread.Sleep(10000);`.

But my reading of the documentation suggests that shouldn't occur. https://docs.flagsmith.com/basic-features/managing-identities#identity-and-trait-storage states:

> Identities are persisted within the Flagsmith platform, along with any Traits that have been assigned to them. When Flags are evaluated for an Identity, the full complement of Traits stored within the platform are used, even if they were not all sent as part of the request.

Which makes me think if I set the trait in one request (and that trait will force them into a segment, and being in that segment should mean the FF is in variant1), then if I ask for the feature flags immediately after (even if I don't pass in the traits again) that I should see flag status based on the traits previously sent through.

_I am aware that in this contrived example I could just pass the `traitList` again, but in the real world the second `GetIdentityFlags` request will be coming from a separate web request that doesn't know about the contents of `traitList`._

**Am I using the C# library incorrectly? How should I be better handling this?**

Segment defined as per these screenshots:

![Image](https://github.com/user-attachments/assets/1da0ff41-019a-4d76-a512-6f1425bbfa12)

![Image](https://github.com/user-attachments/assets/d5a7f7b4-fa1d-4ce9-ae66-e61f90434e7c)

Code sample (NUnit - .NET 8 - Flagsmith 5.4.3 NuGet package - requests being initiated from Australia - tried both client-side and server-side environment key):

```
using Flagsmith;

namespace TestsForFlagSmith
{
    public class IssueForFlagSmith : TestsCommon
    {
        protected static readonly Lazy<FlagsmithClient> _flagsmithClient = new Lazy<FlagsmithClient>(() => new FlagsmithClient("keyhere"));

        [Test]
        public async Task FeatureFlagReflectsCurrentStateOfSegmentAfterTraitsSentInPreviousRequest()
        {
            var identity = Guid.NewGuid().ToString();

            var flags = await _flagsmithClient.Value.GetIdentityFlags(identity);

            var isEnabled = await IsFeatureEnabled(flags, "matthew_ab_test");
            var featureValue = await GetFeatureValue(flags, "matthew_ab_test");

            Assert.False(isEnabled);
            Assert.That(featureValue, Is.EqualTo("baseline"));

            List<ITrait> traitList = [CreateTrait("name", "Matthew")];

            flags = await _flagsmithClient.Value.GetIdentityFlags(identity, traitList);

            isEnabled = await IsFeatureEnabled(flags, "matthew_ab_test");
            featureValue = await GetFeatureValue(flags, "matthew_ab_test");

            Assert.True(isEnabled, "Traits should have been applied");
            Assert.That(featureValue, Is.EqualTo("variant1"));

            // Comment out the next line of code, and the test starts to fail - why?
            // Thread.Sleep(10000);

            flags = await _flagsmithClient.Value.GetIdentityFlags(identity);

            isEnabled = await IsFeatureEnabled(flags, "matthew_ab_test");
            featureValue = await GetFeatureValue(flags, "matthew_ab_test");

            // Remembers the traits from earlier
            Assert.True(isEnabled, "Traits should remain applied");
            Assert.That(featureValue, Is.EqualTo("variant1"));

            Thread.Sleep(10000);

            flags = await _flagsmithClient.Value.GetIdentityFlags(identity);

            isEnabled = await IsFeatureEnabled(flags, "matthew_ab_test");
            featureValue = await GetFeatureValue(flags, "matthew_ab_test");

            // Remembers the traits from earlier
            Assert.True(isEnabled, "Traits should still remain applied");
            Assert.That(featureValue, Is.EqualTo("variant1"));
        }

        private static ITrait CreateTrait(string traitName, string? traitValue)
        {
            return new Trait(traitName, traitValue);
        }


        protected static async Task<bool> IsFeatureEnabled(IFlags flags, string feature)
        {
            try
            {
                return await flags.IsFeatureEnabled(feature);
            }
            catch (FlagsmithClientError ex)
            {
                // FF does not exist
                return false;
            }
        }

        protected static async Task<string> GetFeatureValue(IFlags flags, string feature)
        {
            try
            {
                return await flags.GetFeatureValue(feature);
            }
            catch (FlagsmithClientError ex)
            {
                // FF does not exist
                return null;
            }
        }
    }
}
```

**Comment by matthewelwell** [comment]
@mjwills-k this is likely just because we async the storage of traits, so there is a short delay from traits being sent and traits actually being written to the database. In a unit test, obviously you will be able to create a situation where 2 requests are made within a very short (single digit milliseconds) amount of time, but in a real-life scenario this shouldn't be the case. I'd suspect that if you reduce your sleep to say, 100ms, it will also work. 

In the meantime, I'm going to close this issue because it's behaviour that we are unable to change for performance reasons.

**Comment by mjwills-k** [comment]
Perhaps it would be worth updating https://docs.flagsmith.com/basic-features/managing-identities#identity-and-trait-storage to make that clearer?

**Comment by matthewelwell** [comment]
@mjwills-k I think that's a fair request. I have added that in the PR [here](https://github.com/Flagsmith/flagsmith/pull/4834).
