### ISSUE TITLE
Don't log errors using Console.WriteLine

### ISSUE THREAD

**Issue by jeremywww** [Flagsmith/flagsmith-dotnet-client#20]
Example: https://github.com/Flagsmith/flagsmith-dotnet-client/blob/3334c96192e66eb28ea8ad79e028a0d65ceb38bd/FlagsmithClient.cs#L75

There is no guarantee that the process has a console, and if it doesn't then an attempt to write to the non-existent console can bring down the entire application. Ideally you'd want to use a proper logging framework, but since the usage here is relatively limited you could implement a simple check before writing to the console: `if (Console.WindowHeight > 0) { Console.WriteLine("Error"); }`

**Comment by dabeeeenster** [comment]
Thanks for this - happy to take a PR if you are up for it?!

**Comment by MichaelHochriegl** [comment]
I pulled the latest source code and it seems like this is done already? Otherwise I would have taken a look at it, as we would need all our logging to land in Seq.

**Comment by matthewelwell** [comment]
Thanks @MichaelHochriegl, I'll go ahead and close this issue.
