### ISSUE TITLE
Can't install SDK on new projects

### ISSUE THREAD

**Issue by amunim** [Flagsmith/flagsmith-dotnet-client#32]
I was trying to install the SDK version 4.0.0. on a project that throws the error.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1101	Unable to find package Flagsmith.Engine. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org	Todo	D:\projects\xamarin-forms-samples\Todo\Todo\Todo\Todo.csproj	1	
```
Later, I created a new xamarin project(to check if it works on .Net 6) it still showed the same error while installing the nuget package

_small question_ why doesn't `/flags` API return tags?

**Comment by amunim** [comment]
Is there a way I can attach them, pehaps a flag for it?

**Comment by matthewelwell** [comment]
Hi @amunim, I'm afraid not. It's a design decision that we have taken. There is no way to retrieve the tags from the SDKs.

I am looking into the issues you're having installing the client now.

**Comment by matthewelwell** [comment]
@amunim I have just pushed version 4.0.1 which you should now be able to install? 

Those docs certainly look incorrect to me, I will take a look - thanks for pointing it out.

**Comment by amunim** [comment]
Thanks, it finally worked and I have submitted my article to Matt.
Lastly, can you read it and look at the t4/tt script I embedded, I believe this can help reduce the friction on feature flags, so if you decide on including it on the project it will be useful not only in .NET but other languages too to have constants :)
