### ISSUE TITLE
Flagsmith open feature provider

### ISSUE THREAD

**Issue by vpetrusevici** [Flagsmith/flagsmith-dotnet-client#78]
Hi!
I created a PR for open feature provider implemetation https://github.com/open-feature/dotnet-sdk-contrib/pull/89
Can somebody from Flagsmith make a review to be sure that this is right using of Flagsmith sdk?

Thanks :)

**Comment by matthewelwell** [comment]
Thanks @vpetrusevici - I have added a review there. I will go ahead and lose this issue and we can continue the conversation on the PR thread. Thanks again for submitting the PR, really appreciate it!
